package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// wrapperMarker identifies wrapper scripts written by this tool, so a re-run can
// safely overwrite its own output without clobbering unrelated files.
const wrapperMarker = "# generated by patch-jetbrains-ide"

// BuildWrapperContent returns a POSIX sh script that launches scriptPath
// detached, freeing the calling terminal immediately (like `code .`). nohup +
// background means the IDE also survives the terminal being closed.
func BuildWrapperContent(scriptPath string) string {
	return fmt.Sprintf(
		"#!/bin/sh\n%s -- detaches the launch so the terminal is freed\nnohup %q \"$@\" >/dev/null 2>&1 &\n",
		wrapperMarker, scriptPath,
	)
}

// GenerateWrappers creates a detaching wrapper in targetDir for every launcher
// script found in scriptsDir (the JetBrains Toolbox "scripts" directory).
func GenerateWrappers(scriptsDir, targetDir string, dryRun, repatch bool) {
	entries, readErr := os.ReadDir(scriptsDir)
	if readErr != nil {
		fmt.Fprintf(os.Stderr, "\x1b[31mFailed to read Toolbox scripts directory: %s\x1b[0m\n", scriptsDir)
		os.Exit(1)
	}

	if !dryRun {
		if mkErr := os.MkdirAll(targetDir, 0o755); mkErr != nil {
			fmt.Fprintf(os.Stderr, "\x1b[31mFailed to create target directory: %s\x1b[0m\n", targetDir)
			os.Exit(1)
		}
	}

	fmt.Printf("\x1b[32mGenerating wrappers in %s\x1b[0m\n", targetDir)

	generated := 0
	for _, entry := range entries {
		if entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		name := entry.Name()
		scriptPath := filepath.Join(scriptsDir, name)
		targetPath := filepath.Join(targetDir, name)

		if existing, statErr := os.ReadFile(targetPath); statErr == nil &&
			!strings.Contains(string(existing), wrapperMarker) && !repatch {
			fmt.Printf("\x1b[33mx\x1b[0m %s exists and is not ours; skipping (use -r to overwrite).\n", targetPath)
			continue
		}

		content := BuildWrapperContent(scriptPath)
		if dryRun {
			fmt.Printf("\x1b[32mv\x1b[0m would write %s:\n%s\n", targetPath, content)
			generated++
			continue
		}

		//nolint:gosec // wrapper scripts must be executable
		if writeErr := os.WriteFile(targetPath, []byte(content), 0o755); writeErr != nil {
			fmt.Fprintf(os.Stderr, "\x1b[31mFailed to write wrapper: %s\x1b[0m\n", targetPath)
			os.Exit(1)
		}
		fmt.Printf("\x1b[32mv\x1b[0m %s\n", name)
		generated++
	}

	if generated == 0 {
		fmt.Println("No wrappers generated.")
		return
	}

	if warning := PathOrderWarning(targetDir, scriptsDir, os.Getenv("PATH")); warning != "" {
		fmt.Fprint(os.Stderr, warning)
	}

	if dryRun {
		fmt.Println("\nno action taken -- dry run mode on")
	}
}

// PathOrderWarning returns a non-empty message when the generated wrappers will
// not take effect: either targetDir is not on PATH, or the Toolbox scripts
// directory comes first and would shadow the wrappers. pathEnv is the PATH value
// (os.PathListSeparator-separated). It returns "" when the ordering is correct.
func PathOrderWarning(targetDir, scriptsDir, pathEnv string) string {
	targetIdx, scriptsIdx := -1, -1
	for i, dir := range strings.Split(pathEnv, string(os.PathListSeparator)) {
		clean := filepath.Clean(dir)
		if clean == filepath.Clean(targetDir) && targetIdx == -1 {
			targetIdx = i
		}
		if clean == filepath.Clean(scriptsDir) && scriptsIdx == -1 {
			scriptsIdx = i
		}
	}

	switch {
	case targetIdx == -1:
		return fmt.Sprintf(
			"\x1b[33m! %s is not on PATH; add it before the Toolbox scripts dir for the wrappers to work.\x1b[0m\n",
			targetDir,
		)
	case scriptsIdx != -1 && scriptsIdx < targetIdx:
		return fmt.Sprintf(
			"\x1b[33m! The Toolbox scripts dir precedes %s on PATH, so it shadows the wrappers.\n"+
				"  Move %s earlier in PATH than %s.\x1b[0m\n",
			targetDir, targetDir, scriptsDir,
		)
	default:
		return ""
	}
}
